name: wallet
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sliding_up_panel: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  numberpicker: ^2.1.2
  flutter_numeric_keyboard: ^1.0.3+4
  numeric_keyboard: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/images/ixonwallet.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - lib/images/walletbaground.png

  fonts:
     - family: AntipastoPro
       fonts:
         - asset: lib/fonts/AntipastoPro-Medium_trial.ttf
         
     - family: Azonix
       fonts:
         - asset: lib/fonts/Azonix.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
